parse for wave(strikethrough)
andysim3d/markdown pull request #14
Opened 2020-08-09 05:36 UTC by VCneverdie

2020-08-09 18:27 UTC, andysim3d requested changes

2020-08-09 18:27 UTC, andysim3d commented on strikethrough_block_test.py
> +    ("~~~test")
add \~ case

2020-08-09 18:34 UTC, andysim3d commented on strikethrough_block_test.py
> +    ("~~~test")
**abc****def**

2020-09-01 03:31 UTC, VCneverdie commented on strikethrough_block_test.py
> +    ("~~~test")
more test cases were added

2020-09-09 13:09 UTC, jinglongwu approved these changes

2020-09-09 20:51 UTC, andysim3d approved these changes

2020-09-09 20:52 UTC, merged